# Generated by Django 4.0.2 on 2022-02-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('head0', models.CharField(default='', max_length=5000)),
                ('head1', models.CharField(default='', max_length=5000)),
                ('head2', models.CharField(default='', max_length=5000)),
                ('pub_date', models.DateField()),
                ('Thumbnail', models.ImageField(default='', upload_to='blog/image')),
            ],
        ),
    ]
