# Generated by Django 4.0.2 on 2022-02-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=54)),
                ('email', models.CharField(default='', max_length=100)),
                ('phone', models.IntegerField(default=0)),
                ('message', models.CharField(default='', max_length=2000)),
            ],
        ),
    ]
