# Generated by Django 4.0.2 on 2022-02-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('item_json', models.CharField(max_length=5000)),
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=54)),
                ('email', models.CharField(default='', max_length=100)),
                ('phone', models.IntegerField(default=0)),
                ('adress', models.CharField(max_length=2000)),
                ('city', models.CharField(max_length=2000)),
                ('division', models.CharField(max_length=2000)),
                ('zip_code', models.CharField(max_length=100)),
            ],
        ),
    ]
