# Generated by Django 4.0.2 on 2022-02-20 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_orderupdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderupdate',
            old_name='updat_desc',
            new_name='update_desc',
        ),
    ]
